from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

# 1. Image Metadata Schema
class ImageMetadata(BaseModel):
    image_id: str = Field(..., description="Unique image identifier")
    original_path: str = Field(..., description="File path indicating the Campaign/Season, Brand, and Category")
    campaign: Optional[str] = Field(None, description="Campaign / Season (e.g., Halloween2024)")
    brand: Optional[str] = Field(None, description="Retail Brand (e.g., Tesco, Waitrose)")
    category: Optional[str] = Field(None, description="Product Category (e.g., Food - Floral)")
    store: Optional[str] = Field(None, description="Store / Location")
    capture_date: Optional[date] = Field(None, description="Capture Date")
    quality_score: Optional[float] = Field(None, description="Laplacian Variance score")

# 2. Ontology Hierarchy
class OntologyHierarchy(BaseModel):
    level_1: str = Field(..., description="Location/Space (e.g., Ambient Aisle, Checkout / POS Area)")
    level_2: str = Field(..., description="Structure/Fixture (e.g., Gondola Shelf, End Cap)")
    level_3: str = Field(..., description="Product/Item (GS1 GPC Brick nomenclature)")
    level_4: str = Field(..., description="Operational State (e.g., Empty, Full, Active Promo)")

# 3. Tags Schema
class OntologyTags(BaseModel):
    primary_ontology: OntologyHierarchy = Field(..., description="Primary tags for the image")
    secondary_ontologies: List[OntologyHierarchy] = Field(default_factory=list, description="Secondary/Background tags")
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    gs1_gpc_mapping: Optional[str] = Field(None, description="GS1 GPC mapping derived from L3")

# 4. Routing Matrix Context (Generated by Stage 2)
class RoutingContext(BaseModel):
    persona: str = Field(..., description="Target Persona (e.g., Inventory Manager, Safety Officer)")
    primary_goal: str = Field(..., description="Operational task context assigned")
    
# 5. Final Processed Record
class ProcessedImageRecord(BaseModel):
    metadata: ImageMetadata
    tags: Optional[OntologyTags] = None
    routing_context: Optional[RoutingContext] = None
    reference_caption: Optional[str] = Field(None, description="Final or reference caption")
