"""
Task 13 & 14: MOP Prompt Builder & LLaVA Caption Injection
1. Reads clustered routing data.
2. Loads cluster-specific MOP prompt templates generated by pipeline_4 (Gemini auto-generated).
3. Sends image + MOP prompt to local Ollama VLM model.
4. Generates hallucination-free captions.

10K Resilience features:
- Dict-based checkpoint: already-captioned images skipped on re-run
- Per-image try/except with error logging
- Ollama timeout (30s) to prevent infinite hang on unresponsive model
- Auto-save every 50 images
"""
import os
import json
import ollama
import argparse

IN_PATH = "data/cache/clustered_routes.json"
OUT_PATH = "data/cache/final_captions.json"
MOP_PROMPTS_PATH = "data/cache/mop_prompts.json"
ERROR_LOG = "data/cache/error_log.txt"
AUTOSAVE_INTERVAL = 50
OLLAMA_TIMEOUT = 30  # seconds

# Default VLM model — override via: python pipeline_5_mop_captioning.py --model llava-phi3
# Recommended for RTX 3060 Laptop (6GB VRAM):
#   llava-phi3       (3.8B, ~2.5GB VRAM, 3× faster than llava 7B, recommended)
#   qwen2-vl:2b      (2B,   ~1.5GB VRAM, fastest, strong OCR)
#   llava            (7B,   ~4.5GB VRAM, default but tight on 6GB)
DEFAULT_MODEL = "llava-phi3"


def load_mop_prompts() -> dict:
    """
    Load auto-generated cluster prompts from pipeline_4 output.
    Returns {cluster_id (int): prompt_template (str)}.
    Falls back to a safe generic prompt if the file is missing.
    """
    if os.path.exists(MOP_PROMPTS_PATH):
        with open(MOP_PROMPTS_PATH, "r", encoding="utf-8") as f:
            raw = json.load(f)
        # Keys are stored as strings in JSON — convert back to int
        return {int(k): v["mop_prompt_template"] for k, v in raw.items()}

    print("[WARN] mop_prompts.json not found. Run pipeline_4 first to generate cluster prompts.")
    print("       Falling back to generic MOP prompt for all clusters.")
    return {}

def log_error(img_path: str, error: Exception):
    with open(ERROR_LOG, "a", encoding="utf-8") as f:
        f.write(f"[pipeline_5] {img_path} | {type(error).__name__}: {error}\n")

def load_existing_cache() -> dict:
    """Load previously captioned items as {image_path: item} for checkpoint resumption."""
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            existing = json.load(f)
        return {item["image_path"]: item for item in existing}
    return {}

def save_cache(cache: dict):
    os.makedirs("data/cache", exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(list(cache.values()), f, indent=4, ensure_ascii=False)

def build_mop_prompt(item: dict, mop_prompts: dict) -> str:
    """
    Assembles the final MOP prompt for a given image by:
    1. Filling in the FACTS block from the item's hierarchical tags.
    2. Injecting them into the cluster-specific template from mop_prompts.json.
    Falls back to a minimal generic prompt if the cluster has no template.
    """
    cluster = item.get("MOP_route_cluster", 0)

    l1 = item["L1_scene"]["predicted_scene"]
    l2 = list(item["L2_fixtures"]["fixtures_detected"])
    l2_str = ", ".join(set(l2)) if l2 else "no specific fixtures"

    # Hybrid Extraction with Deduplication — no top-N cap (all factual items)
    top_candidates = item.get("L3_products", {}).get("top_products", [])
    l3_dedup = []
    seen_cores = set()
    for p in top_candidates:
        if p.get("tag_type") == "Absence":
            continue
        product_str = p.get("product", "")
        core = " ".join(product_str.split(" ")[:3]).lower()
        if core not in seen_cores:
            l3_dedup.append(product_str)
            seen_cores.add(core)
    l3_str = ", ".join(l3_dedup) if l3_dedup else "no specific products"

    l0_ctx = item.get("global_context", [])
    ctx_str = ", ".join(l0_ctx) if l0_ctx else "General"

    ops = item["L4_attributes"]["operational_state"]
    stock = ops.get("stock_level", {}).get("label", "unknown stock")
    tidy = ops.get("tidiness", {}).get("label", "unknown tidiness")
    promo = ops.get("promotion", {}).get("label", "unknown promotion")

    ocr_texts = [t["text"] for t in item["L4_attributes"]["ocr_text"][:5]]
    ocr_str = ", ".join(ocr_texts) if ocr_texts else "None"

    # ── Inject FACTS into the cluster-specific template ───────────────────────
    template = mop_prompts.get(cluster)

    if template:
        try:
            return template.format(
                ctx_str=ctx_str, l1=l1, l2_str=l2_str,
                l3_str=l3_str, ocr_str=ocr_str,
                stock=stock, tidy=tidy, promo=promo
            )
        except KeyError as e:
            print(f"  [WARN] Template for cluster {cluster} has unexpected placeholder {e}. Using fallback.")

    # ── Generic fallback (if auto-generated template is missing/broken) ───────
    return f"""[MOP FALLBACK - Cluster {cluster}]
You are a retail merchandising assistant. Describe this image in 2 sentences using ONLY these facts:
- Theme/Context: {ctx_str}
- Area: {l1} | Equipment: {l2_str}
- Items detected: {l3_str}
- Visible Text: {ocr_str}
- Operational Status: {stock}, {tidy}, {promo}
Do NOT invent brand names or hallucinate products not listed above."""

def run_captioning():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"Ollama VLM model name (default: {DEFAULT_MODEL})")
    args = parser.parse_args()
    vlm_model = args.model
    print(f"[VLM] Using model: {vlm_model}")

    with open(IN_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Load auto-generated cluster prompts (produced by pipeline_4)
    mop_prompts = load_mop_prompts()
    print(f"[MOP PROMPTS] Loaded {len(mop_prompts)} cluster-specific templates.")

    # --- Checkpoint: skip already-captioned images ---
    cache = load_existing_cache()
    already_done = len(cache)
    if already_done > 0:
        print(f"[CHECKPOINT] {already_done} captions already generated. Resuming...")

    print(f"Connecting to Local VLM via Ollama for {len(data)} images ({len(data) - already_done} remaining)...")

    new_count = 0
    for item in data:
        img_path = item["image_path"]

        if img_path in cache:
            continue  # Already captioned — skip Ollama call

        print(f"\n--- Generating Caption for {os.path.basename(img_path)} ---")

        try:
            mop_prompt = build_mop_prompt(item, mop_prompts)
            print(f"[MOP Route {item.get('MOP_route_cluster')}] Prompt assembled.")

            response = ollama.chat(
                model=vlm_model,
                messages=[
                    {
                        "role": "user",
                        "content": mop_prompt,
                        "images": [img_path]
                    }
                ],
                options={
                    "temperature": 0.1,
                    "num_ctx": 2048,    # Limit context to reduce VRAM usage on 6GB GPU
                    "timeout": OLLAMA_TIMEOUT
                }
            )

            caption = response['message']['content']
            print(f"VLM Caption:\n{caption}")

            item["FINAL_CAPTION"] = caption
            cache[img_path] = item
            new_count += 1

            # Auto-save every AUTOSAVE_INTERVAL captions
            if new_count % AUTOSAVE_INTERVAL == 0:
                save_cache(cache)
                print(f"  [AUTO-SAVE] Checkpoint at {new_count} new captions (total: {len(cache)}).")

        except Exception as e:
            print(f"  [ERROR] {os.path.basename(img_path)}: {e}")
            print("  Is `ollama serve` running and is the model downloaded?")
            log_error(img_path, e)
            continue

    # Final save
    save_cache(cache)
    print(f"\nAll captions saved to {OUT_PATH}")
    print(f"Generated this session: {new_count} | Total in cache: {len(cache)}")

if __name__ == "__main__":
    run_captioning()
