"""
Task 13 & 14: MOP Prompt Builder & LLaVA Caption Injection
1. Reads clustered routing data.
2. Loads cluster-specific MOP prompt templates generated by pipeline_4 (Gemini auto-generated).
3. Sends image + MOP prompt to local Ollama VLM model.
4. Generates hallucination-free captions.

10K Resilience features:
- Dict-based checkpoint: already-captioned images skipped on re-run
- Per-image try/except with error logging
- Ollama timeout (30s) to prevent infinite hang on unresponsive model
- Auto-save every 50 images
"""
import os
import json
import random
import ollama
import argparse
from collections import Counter

import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
elif sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf-8-sig"):
    sys.stdout = open(sys.stdout.fileno(), mode="w", encoding="utf-8", buffering=1, closefd=False)

SAMPLE_LIST_PATH = "data/cache/sample_image_list.json"  # shared with baseline
ERROR_LOG = "data/cache/error_log.txt"
AUTOSAVE_INTERVAL = 50
OLLAMA_TIMEOUT = 30  # seconds

# Default VLM model — override via: python pipeline_5_mop_captioning.py --model llava-phi3
# Recommended for RTX 3060 Laptop (6GB VRAM):
#   llava-phi3       (3.8B, ~2.5GB VRAM, 3× faster than llava 7B, recommended)
#   qwen2-vl:2b      (2B,   ~1.5GB VRAM, fastest, strong OCR)
#   llava            (7B,   ~4.5GB VRAM, default but tight on 6GB)
DEFAULT_MODEL = "llava-phi3"


def load_mop_prompts(mop_prompts_path: str) -> dict:
    """
    Load auto-generated cluster prompts from pipeline_4 output.
    Returns {cluster_id (int): prompt_template (str)}.
    Falls back to a safe generic prompt if the file is missing.
    """
    if os.path.exists(mop_prompts_path):
        with open(mop_prompts_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        # Keys are stored as strings in JSON — convert back to int
        return {int(k): v["mop_prompt_template"] for k, v in raw.items()}

    print("[WARN] mop_prompts.json not found. Run pipeline_4 first to generate cluster prompts.")
    print("       Falling back to generic MOP prompt for all clusters.")
    return {}

def log_error(img_path: str, error: Exception):
    with open(ERROR_LOG, "a", encoding="utf-8") as f:
        f.write(f"[pipeline_5] {img_path} | {type(error).__name__}: {error}\n")

def load_existing_cache(out_path: str) -> dict:
    """Load previously captioned items as {image_path: item} for checkpoint resumption."""
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            existing = json.load(f)
        return {item["image_path"]: item for item in existing}
    return {}

def save_cache(cache: dict, out_path: str):
    os.makedirs("data/cache", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(list(cache.values()), f, indent=4, ensure_ascii=False)

# ── L4 label → natural language helpers ─────────────────────────────────────

_STOCK_MAP = {
    "tightly packed":          "shelves appear well-stocked",
    "missing items": "some visible shelf gaps",
    "completely empty":     "shelves appear empty",
}
_TIDY_MAP = {
    "perfectly neat":  "neatly organised",
    "messy, disorganized": "display appears disorganised",
}
_PROMO_MAP = {
    "highly visible promotional":    "promotional signage is visible",
    "no promotional signs":   None,
}


def _l4_to_natural(ops: dict) -> tuple[str, list]:
    """
    Convert L4 operational_state dict to:
      - obs_str   : observable facts expressed in natural language
      - ambiguous : list of attribute names that are 'Ambiguous' → VLM must not guess
    """
    observations = []
    ambiguous    = []

    for attr, label_map, friendly_name in [
        ("stock_level", _STOCK_MAP, "stock level"),
        ("tidiness",    _TIDY_MAP,  "tidiness"),
        ("promotion",   _PROMO_MAP, "promotional status"),
    ]:
        entry = ops.get(attr, {})
        label = entry.get("label", "")
        label_lc = label.lower()

        if "ambiguous" in label_lc or "unclear" in label_lc or "cannot" in label_lc:
            ambiguous.append(friendly_name)
        else:
            # Find first map key that appears in the label
            mapped = None
            for key, val in label_map.items():
                if key in label_lc:
                    mapped = val
                    break
            if mapped:  # None means "omit" (e.g. 'no promotion')
                observations.append(mapped)

    obs_str = "; ".join(observations) if observations else ""
    return obs_str, ambiguous


def build_mop_prompt(item: dict, mop_prompts: dict) -> str:  # noqa: C901
    """
    Assembles the final MOP prompt using Open+Anchor strategy:
      - VLM is free to describe what it sees (preserves visual/seasonal context)
      - L3 verified products are ANCHORS that must appear in the caption
      - Ambiguous L4 attributes are EXPLICITLY flagged — VLM must not guess
      - Raw OCR is NOT injected (L3 Gemini tagging already consumed it)
    """
    cluster = item.get("MOP_route_cluster", 0)

    # ── L1 / L2 ───────────────────────────────────────────────────────────────
    l1 = item["L1_scene"]["predicted_scene"]
    
    # Extract unique words from fixtures (handles 'display box display bin' -> 'display box bin')
    l2_words = []
    for f in item["L2_fixtures"]["fixtures_detected"]:
        for word in f.split():
            if word not in l2_words:
                l2_words.append(word)
    
    l2_str = ", ".join(l2_words) if l2_words else "unspecified fixtures"

    # ── L0 global context (background only, not a hard constraint) ────────────
    l0_ctx = item.get("global_context", [])
    ctx_str = ", ".join(l0_ctx) if l0_ctx else ""

    # ── L3 products: only Hard/Soft-tagged, deduplicated, no Absence ──────────
    l3_source      = item.get("l3_source", "gemini")
    top_candidates = item.get("L3_products", {}).get("top_products", [])
    l3_anchors = []
    if l3_source != "empty":
        seen_cores = set()
        for p in top_candidates:
            if p.get("tag_type") == "Absence":
                continue
            # Minimum confidence gate (Hard >= 0.55, Soft >= 0.30)
            conf = p.get("confidence", 0)
            tag_type = p.get("tag_type", "")
            if tag_type == "Hard" and conf < 0.55:
                continue
            if tag_type == "Soft" and conf < 0.30:
                continue
            product_str = p.get("product", "")
            core = " ".join(product_str.split()[:3]).lower()
            if core and core not in seen_cores:
                l3_anchors.append(product_str)
                seen_cores.add(core)

    # ── L4 → natural language ─────────────────────────────────────────────────
    ops = item["L4_attributes"]["operational_state"]
    obs_str, ambiguous = _l4_to_natural(ops)

    # ── Compose section strings ───────────────────────────────────────────────
    anchor_section = (
        "Verified products / items (MUST be mentioned):\n  - "
        + "\n  - ".join(l3_anchors)
        if l3_anchors else
        "No specific products could be verified from this image."
    )

    ambiguous_section = (
        "Do NOT state or guess the following — they cannot be confirmed:\n  - "
        + "\n  - ".join(ambiguous)
        if ambiguous else
        ""
    )

    observation_hint = (
        f"Observed operational details (include naturally if visible):\n  {obs_str}\n"
        if obs_str else ""
    )

    # ── Full Open+Anchor prompt ───────────────────────────────────────────────
    # NOTE: global_context (L0) is intentionally NOT injected into the VLM prompt.
    # It is stored in the JSON for internal pipeline use (e.g. Pipeline 3c, 8)
    # but passing metadata like 'Year 2014' to the VLM caused hallucinations.
    prompt = f"""You are a professional retail analyst. Write 2-3 sentences in natural, flowing prose. Do not use titles, bullet points, numbered lists, or headers.

RULES:
1. Describe what you actually SEE: scene type, layout, colours, arrangement, seasonal themes.
2. You MUST mention the following VERIFIED items — they are confirmed present:
   {anchor_section}
3. {ambiguous_section if ambiguous_section else 'State operational details only when clearly visible.'}
4. Do NOT invent brand names, products, or prices beyond what is verified above.

{observation_hint}Scene type: {l1} | Fixtures: {l2_str}

Write your caption now:"""

    # ── Cluster template override (if pipeline_4 has generated a matching one) -
    # NOTE: legacy closed-world templates are intentionally skipped here.
    # Only use Gemini-generated templates that contain the keyword 'MUST' or
    # 'anchor' to confirm they follow the Open+Anchor style.
    template = mop_prompts.get(cluster, "")
    if template and ("MUST" in template or "anchor" in template.lower()):
        try:
            return template.format(
                ctx_str=ctx_str, l1=l1, l2_str=l2_str,
                l3_str="\n  - ".join(l3_anchors) if l3_anchors else "none verified",
                obs_str=obs_str,
                ambiguous=" | ".join(ambiguous) if ambiguous else "none",
            )
        except KeyError as e:
            print(f"  [WARN] Cluster {cluster} template has unknown placeholder {e}. Using generic.")

    return prompt

def stratified_sample(data: list, n: int) -> list:
    """Pick n images stratified across MOP clusters."""
    clusters = Counter(item.get("MOP_route_cluster", 0) for item in data)
    unique = sorted(clusters.keys())
    n_clusters = len(unique)
    base = n // n_clusters
    remainder = n % n_clusters
    sampled = []
    for i, cluster in enumerate(unique):
        quota = base + (1 if i < remainder else 0)
        items_in_cluster = [x for x in data if x.get("MOP_route_cluster") == cluster]
        sampled.extend(items_in_cluster[:quota])
    return sampled[:n]


def run_captioning():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"Ollama VLM model name (default: {DEFAULT_MODEL})")
    parser.add_argument("--sample", type=int, default=None,
                        help="Only process N images (stratified by cluster). Writes sample list for baseline.")
    parser.add_argument("--from-sample-list", action="store_true",
                        help="Instead of sampling, use the exact images listed in sample_image_list.json (for fair ablation).")
    parser.add_argument("--suffix", type=str, default="",
                        help="Suffix for K-selection ablation (e.g. 'k2' or 'k4'). If provided, appends _suffix to filenames.")
    args = parser.parse_args()
    vlm_model = args.model
    suffix_str = f"_{args.suffix}" if args.suffix else ""
    
    in_path = f"data/cache/clustered_routes{suffix_str}.json"
    out_path = f"data/cache/final_captions{suffix_str}.json"
    mop_prompts_path = f"data/cache/mop_prompts{suffix_str}.json"
    
    print(f"[VLM] Using model: {vlm_model}")
    print(f"[PATHS] Input: {in_path} | Output: {out_path} | Prompts: {mop_prompts_path}")

    with open(in_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if args.from_sample_list:
        if not os.path.exists(SAMPLE_LIST_PATH):
            raise FileNotFoundError(f"--from-sample-list used, but {SAMPLE_LIST_PATH} not found.")
        with open(SAMPLE_LIST_PATH, "r", encoding="utf-8") as f:
            valid_paths = set(json.load(f))
        data = [item for item in data if item["image_path"] in valid_paths]
        print(f"[SAMPLE] Loaded {len(data)} images exactly matching {SAMPLE_LIST_PATH}.")
    elif args.sample:
        data = stratified_sample(data, args.sample)
        print(f"[SAMPLE] Stratified sample: {len(data)} images across clusters.")
        # Write shared sample list so baseline can process exact same images
        sample_paths = [item["image_path"] for item in data]
        os.makedirs("data/cache", exist_ok=True)
        with open(SAMPLE_LIST_PATH, "w", encoding="utf-8") as f:
            json.dump(sample_paths, f, indent=2)
        print(f"[SAMPLE] Sample list written → {SAMPLE_LIST_PATH}")

    # Load auto-generated cluster prompts (produced by pipeline_4)
    mop_prompts = load_mop_prompts(mop_prompts_path)
    print(f"[MOP PROMPTS] Loaded {len(mop_prompts)} cluster-specific templates.")

    # --- Checkpoint: skip already-captioned images ---
    cache = load_existing_cache(out_path)
    already_done = len(cache)
    if already_done > 0:
        print(f"[CHECKPOINT] {already_done} captions already generated. Resuming...")

    print(f"Connecting to Local VLM via Ollama for {len(data)} images ({len(data) - already_done} remaining)...")

    new_count = 0
    for item in data:
        img_path = item["image_path"]

        if img_path in cache:
            continue  # Already captioned — skip Ollama call

        print(f"\n--- Generating Caption for {os.path.basename(img_path)} ---")

        try:
            mop_prompt = build_mop_prompt(item, mop_prompts)
            print(f"[MOP Route {item.get('MOP_route_cluster')}] Prompt assembled.")

            response = ollama.chat(
                model=vlm_model,
                messages=[
                    {
                        "role": "user",
                        "content": mop_prompt,
                        "images": [img_path]
                    }
                ],
                options={
                    "temperature": 0.1,
                    "num_ctx": 2048,    # Limit context to reduce VRAM usage on 6GB GPU
                    "timeout": OLLAMA_TIMEOUT
                }
            )

            caption = response['message']['content']
            print(f"VLM Caption:\n{caption}")

            item["FINAL_CAPTION"] = caption
            cache[img_path] = item
            new_count += 1

            # Auto-save every AUTOSAVE_INTERVAL captions
            if new_count % AUTOSAVE_INTERVAL == 0:
                save_cache(cache, out_path)
                print(f"  [AUTO-SAVE] Checkpoint at {new_count} new captions (total: {len(cache)}).")

        except Exception as e:
            print(f"  [ERROR] {os.path.basename(img_path)}: {e}")
            print("  Check if `ollama serve` is running and the model is downloaded.")
            log_error(img_path, e)
            continue

    # Final save
    save_cache(cache, out_path)
    print(f"\nAll captions saved to {out_path}")
    print(f"Generated this session: {new_count} | Total in cache: {len(cache)}")

if __name__ == "__main__":
    run_captioning()
